version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: service-management-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
      - ./cmd/migration/init.sql:/docker-entrypoint-initdb.d/init.sql
  swagger-ui:
  # Switch image for arm64 chip
  #  image: spryker/swagger-ui:v3.24.3
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_container
   ports:
      - "8082:8080"
   volumes:
      - ./openapi/api:/usr/share/nginx/html/openapi/api
   environment:
      API_URL: openapi/api/swagger.yaml