/*
 * Service Managemenet
 *
 * This is a sample proof of concept repo meant to be run on localhost at the moment
 *
 * API version: 1.0.0
 * Contact: diegosegundo2@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateServiceRequest struct {
	// Unique Title of the service
	Title string `json:"title,omitempty"`
	// description of the service
	Description string `json:"description,omitempty"`
}
