/*
 * Service Managemenet
 *
 * This is a sample proof of concept repo meant to be run on localhost at the moment
 *
 * API version: 1.0.0
 * Contact: diegosegundo2@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListServicesResponse struct {
	// Total number of objects found not only on this page
	TotalCount int32 `json:"total_count,omitempty"`
	// List of services
	Services []Service `json:"services,omitempty"`
}
