/*
 * Service Managemenet
 *
 * This is a sample proof of concept repo meant to be run on localhost at the moment
 *
 * API version: 1.0.0
 * Contact: diegosegundo2@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Empty object for return value
type Empty struct {
}
