/*
 * Service Managemenet
 *
 * This is a sample proof of concept repo meant to be run on localhost at the moment
 *
 * API version: 1.0.0
 * Contact: diegosegundo2@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateServiceRequest struct {
	// id of the service to update
	ServiceId string `json:"service_id,omitempty"`
	// title for the service to update
	Title string `json:"title,omitempty"`
	// new description of the service to update
	Description string `json:"description,omitempty"`
}
